### ISSUE TITLE
When I try to launch on app its crashing. Actually when I try to connect voice chat in a room.

### ISSUE THREAD

**Issue by yavuz1205** [dalovar/league-of-legends-voice-chat-on-mac#5]

**Comment by Quickshadoww** [comment]
same for me

**Comment by nixtoshi** [comment]
@xphreak5 @Quickshadoww Is this still an issue? Usually these random issues pop up on new updates and get resolved on their own, probably by Riot, and usually there isn't much I can do on my end to solve these

**Comment by yavuz1205** [comment]
Sadly it has still no function on my mac. Maybe it would work on intel macs. Anyways still waiting the patch from Riot :,)

**Comment by nixtoshi** [comment]
The issue seems to be with M1, my solution works fine on intel based and older macs. Never upgraded to M1 and not planning on offering more free support for this fix.

Possible, never upgraded to M1. Many seem to use it without issue on other macs.

I would recommend that you use **Discord** for voice instead. Most gamers use discord for all games anyways.

If Discord causes a higher ping (it usually does), use it through a mobile hotspot or a different internet connection.
