### ISSUE TITLE
League client closes when connecting to Voice Chat via this launcher

### ISSUE THREAD

**Issue by simon-hayden** [dalovar/league-of-legends-voice-chat-on-mac#7]
On my Intel i9 MacBook Pro (16-inch, 2019) this causes the following error as soon as you connect to LoL Voice chat when running the client via your launcher:

"You've lost connection to our services, please restart the client to fix the issue. If this issue persists, please contact player support."

On the other hand, it works perfectly with voice on my partner's M1 Macbook Air.

Can anyone confirm recent success on Intel-based Macs running latest MacOS (12.4) and LoL Client (12.10.4422.9993)?

**Comment by nixtoshi** [comment]
Hey. I have an intel based macbook but no longer play so I can't test it.

I've noticed a couple people opening issues this year, so this is probably related to MacOS updates for M1 macs.

If you have an Intel-based macbook, I would not recommend updating from macOS Catalina (10.15.7 at latest) because the updates after this one aren't optimized for Intel, but for M1 chips.

**Comment by taylorkline** [comment]
Same issue here.

**Comment by taylorkline** [comment]
Did it ever work for you again @simon-hayden ?

**Comment by simon-hayden** [comment]
Haven't tried since with more recent versions of macOS or League client? Gave up and using Discord instead.

**Comment by nixtoshi** [comment]
The issue seems to be with M1, my solution works fine on intel based and older macs. Never upgraded to M1 and not planning on offering more free support for this fix.

Never upgraded to M1. Many seem to use it without issue on other macs like intel-based.

I would recommend that you use **Discord** for voice instead. Most gamers use discord for all games anyways.

If Discord causes a higher ping (it usually does), use it through a mobile hotspot or a different internet connection.
